export const filteredSalons = [
  {
    id: 1,
    name: 'TopG Wagon',
    address: '123 Main St Maison Alfor Neuilly la pelouse sur seine1 wash, Cityville',
    reviewsNumber: 120,
    rate: 4.5,
    openingHours: 'Mon-Sun: 9:00 AM - 8:00 PM',
  },
  {
    id: 2,
    name: 'Elite Salon',
    address: '456 Elm St, Townsville',
    reviewsNumber: 98,
    rate: 4.2,
    openingHours: 'Mon-Sat: 10:00 AM - 6:00 PM',
  },
  {
    id: 3,
    name: 'Glamour Cuts',
    address: '789 Oak St, Villagetown',
    reviewsNumber: 150,
    rate: 4.8,
    openingHours: 'Tue-Sun: 11:00 AM - 7:00 PM',
  },
  {
    id: 4,
    name: 'Urban Chic',
    address: '321 Pine St, Metropolis',
    reviewsNumber: 200,
    rate: 4.7,
    openingHours: 'Mon-Fri: 9:00 AM - 5:00 PM, Sat: 10:00 AM - 4:00 PM',
  },
  {
    id: 5,
    name: 'Luxury Nails',
    address: '654 Cedar St, Cosmopolis',
    reviewsNumber: 85,
    rate: 4.3,
    openingHours: 'Mon-Sun: 10:00 AM - 8:00 PM',
  },
  {
    id: 6,
    name: 'The Style Hub',
    address: '987 Spruce St, Capital City',
    reviewsNumber: 112,
    rate: 4.6,
    openingHours: 'Wed-Sun: 12:00 PM - 6:00 PM',
  },
  {
    id: 7,
    name: 'Beauty Bar',
    address: '222 Maple St, Urbantown',
    reviewsNumber: 134,
    rate: 4.4,
    openingHours: 'Mon-Sat: 8:30 AM - 7:00 PM',
  },
  {
    id: 8,
    name: 'Trendy Styles',
    address: '333 Birch St, Cityscape',
    reviewsNumber: 90,
    rate: 4.1,
    openingHours: 'Tue-Sun: 9:00 AM - 6:30 PM',
  },
  {
    id: 9,
    name: 'Classic Cuts',
    address: '444 Palm St, Seaside',
    reviewsNumber: 102,
    rate: 4.2,
    openingHours: 'Mon-Sun: 10:00 AM - 9:00 PM',
  },
  {
    id: 10,
    name: 'Hair & Beyond',
    address: '555 Cypress St, Uptown',
    reviewsNumber: 76,
    rate: 4.0,
    openingHours: 'Mon-Fri: 8:00 AM - 5:30 PM',
  },
  {
    id: 11,
    name: 'TopG Wagon',
    address: '123 Main St, Cityville',
    reviewsNumber: 120,
    rate: 4.5,
    openingHours: 'Mon-Sun: 9:00 AM - 8:00 PM',
  },
  {
    id: 12,
    name: 'Elite Salon',
    address: '456 Elm St, Townsville',
    reviewsNumber: 98,
    rate: 4.2,
    openingHours: 'Mon-Sat: 10:00 AM - 6:00 PM',
  },
  {
    id: 13,
    name: 'Glamour Cuts',
    address: '789 Oak St, Villagetown',
    reviewsNumber: 150,
    rate: 4.8,
    openingHours: 'Tue-Sun: 11:00 AM - 7:00 PM',
  },
  {
    id: 14,
    name: 'Urban Chic',
    address: '321 Pine St, Metropolis',
    reviewsNumber: 200,
    rate: 4.7,
    openingHours: 'Mon-Fri: 9:00 AM - 5:00 PM, Sat: 10:00 AM - 4:00 PM',
  },
  {
    id: 15,
    name: 'Luxury Nails',
    address: '654 Cedar St, Cosmopolis',
    reviewsNumber: 85,
    rate: 4.3,
    openingHours: 'Mon-Sun: 10:00 AM - 8:00 PM',
  },
  {
    id: 16,
    name: 'The Style Hub',
    address: '987 Spruce St, Capital City',
    reviewsNumber: 112,
    rate: 4.6,
    openingHours: 'Wed-Sun: 12:00 PM - 6:00 PM',
  },
];
